### ISSUE TITLE
missing user setting in chrome and chords 

### ISSUE THREAD

**Issue by Harmogu** [chordbook/chordbook#838]
![1](https://user-images.githubusercontent.com/97497029/218730617-80f76c86-c675-42f6-87be-1d45df0c85a4.PNG)
![Capture](https://user-images.githubusercontent.com/97497029/218730632-e61d8e04-d4a2-42bf-ad1d-405b7b1e22aa.PNG)

**Comment by bkeepers** [comment]
Hi @Harmogu, thanks for opening an issue. I can't tell from the screenshots what you were trying to do when you got the error. Can you give steps to reproduce the issue?

**Comment by bkeepers** [comment]
@Harmogu I just pushed fixes for both of the issues you reported. You may need to close the tab and reopen it for the app to update.
